### ISSUE TITLE
Expired domain

### ISSUE THREAD

**Issue by lightswitch05** [cloudflare/mitm.watch#6]
It seems `mitm.watch` domain has expired. I suppose this project has been abandoned? Are there any recommended alternatives?

**Comment by Lekensteyn** [comment]
The project has indeed been abandoned because TLS 1.3 has successfully been rolled out, and the underlying technology on which this project was built has been removed. This repo will likely be archived soon.

Adobe Flash is no longer supported or available in web browsers, so this tool cannot create connections to servers anymore.

Is there any particular functionality that you are looking for?

**Comment by lightswitch05** [comment]
I was just following up on a [stackoverflow question](https://superuser.com/questions/505772/how-can-i-find-out-if-there-is-a-proxy-between-myself-and-the-internet-if-there/1358907?noredirect=1#comment2922697_1358907) about it being a dead link, its not something I need. Thanks for the info!
